In [ ]:
import numpy as np
import pandas as pd
def compute_gradient(w,b,x_train,y_train):
    for i in range(len(x_train)):
        f_w = w*x_train[i] + b
        new = f_w-y_train[i]
        new = new*x_train[i]
        f_b = w*x_train[i] + b
        new1 = f_b-y_train[i]
    return new/len(x_train), new1/len(x_train)




def cost_fintion(w,b,x_train,y_train):
    for i in range(len(x_train)):

        f_wb = w*x_train[i] + b
        f_wd = f_wb-y_train[i]
        fw = f_wd**2
    return fw/len(x_train)


iteration = 10000
x_train = np.array([1.0, 2.0])   #features
y_train = np.array([300.0, 500.0]) 
alpha = 0.01
w = 0
b = 0

for i in range(iteration):
    f_w,f_b = compute_gradient(w,b,x_train,y_train)
    print(cost_fintion(w,b,x_train,y_train))
    w = w-alpha*f_w
    b = b-alpha*f_b

print(w*1+b)
print(w*2+b)



implemetation of linear regression multiveribale


In [ ]:
import numpy as np 
import pandas as pd

X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])


In [ ]:
w = [0,0,0,0]

In [ ]:
import numpy as np
def f_x(w,b,x):
    delta_w = 0
    for i in range(len(x)):
        for j in range(len(x[i])):
            delta_w += x[i][j]*w[j]
    delta_w+=b
    return  delta_w


def compute_gredient(w,b,X_train,y_train,):
    dj_dw = np.zeros((X_train.shape[1],))
    dj_db= 0
    
    for i in range(len(X_train)):
        delta = f_x(w,b,X_train)
        delta = delta - y_train[i]
        print(delta)

        for j in range(len(X_train[1])):
            dj_dw[j] = dj_dw[j] + delta*X_train[i,j]
        dj_db = dj_db +delta
    # print(dj_dw)
    return dj_dw/len(X_train), dj_db/len(X_train)


iterrations = 1000
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
w = np.zeros((X_train.shape[1],))
print(w)
alpha = 0.001
b = 0
for i in range(iterrations):
    # print(w)
    dj_dw,dj_db = compute_gredient(w,b,X_train,y_train)
    w = w-alpha*dj_dw
    b = b- alpha*dj_db

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

new = ['size(sqft)','bedrooms','floors','age',"price"]
df = pd.read_csv("houses.txt",names=new)
X_train = df.iloc[:,:4]
y = df.iloc[:,4]
# print(X_train)
print(y)

In [ ]:
size,ax = plt.subplots(1,4,figsize =(12,3),sharey=True)
# print(size)
# print(ax)
for i in range(len(ax)):
    ax[i].scatter(X_train.iloc[:,i],y)
    ax[i].set_xlabel(new[i])

# ax[i+1].scatter(X_train.iloc[:,i+1],y)
ax[0].set_ylabel(new[-1])
plt.show()




In [ ]:
import math 
import copy
import numpy as np
import pandas as pd
def compute_gradient(X, y, w, b): 

    m,n = X.shape           
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * X[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_db, dj_dw



initial_w = np.array([0,0,0,0])
initial_b = 0.
num_iters = 1000
alpha = 5.0e-7

w = copy.deepcopy(initial_w)  
b = initial_b
X = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y = np.array([460, 232, 178])
for i in range(num_iters):

    dj_db,dj_dw = compute_gradient(X, y, w, b)   

    w = w - alpha * dj_dw               
    b = b - alpha * dj_db               
    


In [ ]:
# w
# b

In [ ]:
import math 
import copy
import numpy as np
import pandas as pd
def compute_gradient(X, y, w, b): 

    m,n = X.shape           
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * X[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_db, dj_dw


initial_w = np.array([0,0,0,0])
initial_b = 0.
num_iters = 1000
alpha = 5.0e-7


# loading the data part 
new = ['size(sqft)','bedrooms','floors','age',"price"]
df = pd.read_csv("houses.txt",names=new)
X_train = df.iloc[:,:4]
y = df.iloc[:,4]


In [ ]:
import matplotlib.pyplot as plt

fig,ax = plt.subplots(1,4,figsize=(10,3),sharey=True)
# plt.show()
for i in range(len(ax)):
    ax[i].scatter(df.iloc[:,i],y)
    ax[i].set_xlabel(new[i])
# ax[0].scatter(df.iloc[:,-1])
ax[0].set_ylabel(str(new[-1])+ "in (1000's)")



In [ ]:
# fig,ax=plt.subplots(1, 4, figsize=(12, 3), sharey=True)


In [ ]:
# X_train = df.iloc[:,:4]
# print(X_train)
l = []
for i in range(len(X_train)):
    l.append(X_train.iloc[i,:].values)

new_X_train = np.array(l)
new_y_train = y.values


In [ ]:
# new_X_train
# new_y_train

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])


m,n = X_train.shape
print(m,n)



In [ ]:
def compute_grdient(w,b,x,y):
    var = compute_cost(w,b,x,y)
    dj_dw = np.array([0,0,0,0])
    dj_db = 0
    for i in range(m):
        err = (np.dot(x[i],w)+b) -y[i]
        print(err)
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err*x[i,j]
        dj_db = dj_db + err

    return dj_dw/m, dj_db/m,var

        

# anand()

def compute_cost(w,b,X_train,y):
    counter = 0
    for i in range(len(X_train)):
        err = (np.dot(X_train[i],w)+b) -y[i]
        counter = counter +err**2
    return counter/(2*len(X_train))
    




iteration = 1000
alpha = 5.0e-7
w = np.array([0,0,0,0])
b = 0
cost_funtion_list = []
for  i in range(iteration):
    
    dj_dw, dj_db,var = compute_grdient(w,b,X_train,y_train)

    cost_funtion_list.append(var)

    w = w - alpha*dj_dw
    b = b- alpha*dj_db






In [ ]:
# print(w)
cost_funtion_list
plt.plot(cost_funtion_list)
plt.show()
plt.plot(cost_funtion_list[100:])
plt.show()


In [ ]:
import matplotlib.pyplot as plt
size,(ax1,ax2) = plt.subplots(1,2,)

In [ ]:
import matplotlib.pyplot as plt


def example_plot(ax):
    ax.plot([1, 2])
    ax.set_xlabel('x-label', fontsize=12)
    ax.set_ylabel('y-label', fontsize=12)
    ax.set_title('Title', fontsize=14)

fig, axs = plt.subplots(nrows=2, ncols=2, constrained_layout=True)
print(axs.flat)
# for i in range(leb)
for ax in axs.flat:
    print(ax)
#     example_plot(ax)

In [ ]:
print(100+np.arange(len(cost_funtion_list[100:])))

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


delta = ['size(sqft)','bedrooms','floors','age',"price"]

df = pd.read_csv("houses.txt",names=['size(sqft)','bedrooms','floors','age',"price"])

# df
X_train = df.iloc[:,:4].to_numpy()
y  = df.iloc[:,4].to_numpy()

# print(X_train.to_numpy())
# print(y.to_numpy())

# def 
# check the data 
size,ax = plt.subplots(1,4,figsize=(10,3),sharey=True)
for i in range(len(ax)):
    ax[i].scatter(df.iloc[:,i],y)
    ax[i].set_xlabel(delta[i])
ax[0].set_ylabel(delta[-1])





In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


delta = ['size(sqft)','bedrooms','floors','age',"price"]

df = pd.read_csv("houses.txt",names=['size(sqft)','bedrooms','floors','age',"price"])

def comupte_grdient(w,b,x_train,y_train):
    dw_dj = np.zeros(4)
    m,n = x_train.shape
    db_dj = 0
    cost = compute_cost(w,b,x_train,y_train)
    for i in range(m):
        err = (np.dot(x_train[i],w) +b)-y_train[i]
        for j in range(n):
            
            dw_dj[j] = dw_dj[j] + err*x_train[i,j]
            # print(dw_dj)

        db_dj+=err
    return dw_dj/m,db_dj/m,cost

    
def compute_cost(w,b,x_train,y_train):
        # dw_dj = np.zeros(4)
    m,n = x_train.shape
    # db_dj = 0
    j_w_b = 0
    for i in range(m):
        j_w_b+=((np.dot(x_train[i],w) +b)-y_train[i])**2
    return j_w_b/(2*m)
    

itertion = 10
w = np.array([0,0,0,0,])
b = 0
alpha = 9.9e-7
X_train = df.iloc[1:,:4].to_numpy()
y  = df.iloc[1:,4].to_numpy()


my_dic = {}
my_dic["cost"] = []
my_dic["iteration"] = []
my_dic["parameters"] = []



for i in range(itertion):

    dw_dj,db_dj,cost = comupte_grdient(w,b,X_train,y)
    w = w-alpha*dw_dj
    b = b-alpha*db_dj
    

    my_dic["cost"].append(cost)
    my_dic["iteration"].append(i)
    my_dic["parameters"].append([w,b])




        


In [ ]:
# print(my_dic["iteration"])
# for i in my_dic["parameters"]:
#     print(i)
ws = np.array([i[0] for i in my_dic["parameters"]])
print(ws[:,0])

rng = max(abs(ws[:,0].max()),abs(ws[:,0].min()))


In [ ]:
import matplotlib.pyplot as plt


size,ax = plt.subplots(1,2,figsize=(10,3))
ax[0].plot(my_dic["iteration"],my_dic["cost"])
ax[0].set_title("Iteration vs cost")
ax[0].set_ylabel("Cost")
ax[0].set_xlabel("Iteration")
ax[1].plot(ws[:,0],my_dic["cost"])
ax[1].set_title("w[0] vs cost")
ax[1].set_ylabel("Cost")
ax[1].set_xlabel("w[0]")
plt.show()


In [ ]:
import numpy as np
l = [list(range(6)),list(range(6,12)),list(range(12,18)),list(range(18,24))]

# print(l)
l = [np.array(i) for i in l]
l = np.array(l)
print(l)

hwllo = np.mean(l,axis=0)
print(hwllo)


hwllo = np.mean(l,axis=1)
print(hwllo)

In [ ]:
x = np.arange(0, 20, 1)
y = 1 + x**2
X = x.reshape(-1, 1)    

print(y)
m,n = X.shape

def compute_grident(w,b,x,y):
    dw_dj = np.zeros((n,))
    dj_db = 0


    for i in range(len(x)):
        err = np.dot(x[i],w)-y[i]
        for j in range(n):
            dw_dj[j] = dw_dj[j]+err*x[i,j]
        dj_db = dj_db+err
    
    dw_dj = dw_dj/m
    dj_db = dj_db/m

    return dw_dj,dj_db


w = np.zeros((n,))
b = 0
w_answer,d_answer = compute_grident(w,b,X,y)
print(w_answer,d_answer)




In [ ]:
def compute_gradient_matrix(X, y, w, b): 
    """
    Computes the gradient for linear regression 
 
    Args:
      X : (array_like Shape (m,n)) variable such as house size 
      y : (array_like Shape (m,1)) actual value 
      w : (array_like Shape (n,1)) Values of parameters of the model      
      b : (scalar )                Values of parameter of the model      
    Returns
      dj_dw: (array_like Shape (n,1)) The gradient of the cost w.r.t. the parameters w. 
      dj_db: (scalar)                The gradient of the cost w.r.t. the parameter b. 
                                  
    """
    m,n = X.shape
    f_wb = X @ w + b              
    e   = f_wb - y                
    dj_dw  = (1/m) * (X.T @ e)    
    dj_db  = (1/m) * np.sum(e)    
        
    return dj_db,dj_dw

w = np.zeros((n,))
b = 0
w_answer,w_answer = compute_gradient_matrix(w,b,X,y)
print(w_answer,w_answer)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers  import Dense,Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError,BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)



In [ ]:
size,ax = plt.subplots(1,1,figsize=(8,6))
ax.scatter(X_train,Y_train,marker="x",c="b",label="data points")
ax.legend(fontsize="xx-large")
ax.set_ylabel("Price (in 1000s of dollars)")
ax.set_xlabel("size ")
# ax.title("House_price (in 1000s of dollars) vs Size (in 1000s of sqfeet)")
plt.show()

In [ ]:
layer1 = tf.keras.layers.Dense(units=1,activation="linear",)

In [ ]:
layer1.get_weights()

In [ ]:
# a1 = layer1(X)
# print(X_train[0].reshape(1,1))
a1 = layer1(X_train[0].reshape(1,1))
print(a1)
print(a1.numpy())

In [ ]:
# layer1.get_weights()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import BinaryCrossentropy,MeanSquaredError


In [ ]:
X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32) 


size,ax = plt.subplots(1,1,figsize=(8,5))
ax.scatter(X_train,Y_train,marker="x",c="r",label="data-points")
ax.legend(fontsize="xx-large")
# ax.show()
plt.show()

In [ ]:
layer1 = tf.keras.layers.Dense(units=1,activation="linear")

In [ ]:
layer1.get_weights()



In [ ]:
# print(X_train[0].reshape(1,1))
a1 = layer1(X_train[0].reshape(1,1))
print(a1.numpy())
print(a1)

In [ ]:
w,b=layer1.get_weights()
print(w,b)

In [ ]:
import numpy as np
k = np.arange(6)
print(k.reshape(3,2))

In [ ]:
set_w = np.array([[200]])
set_b = np.array([100])
layer1.set_weights([set_w,set_b])
layer1.get_weights()

In [ ]:
a1 = layer1(X_train[0].reshape(1,1))
a1in = np.dot(set_w,X_train[0].reshape(1,1)) + set_b
a1in

In [ ]:
# print(X_train)
import  matplotlib.pyplot as plt
delta = layer1(X_train)
delta1 = np.dot(X_train,set_w) + set_b
# print(delta)
# print(delta1)

size,ax = plt.subplots(1,2,figsize=(20,6),sharey=True)
for i in range(len(ax)):
    # print("hello")
    ax[i].scatter(X_train,Y_train,marker="x",c="r")
ax[0].plot(X_train,delta,label="tenserflow calucations")
ax[1].plot(X_train,delta1,label="numpy evalutions")
ax[0].legend(fontsize="xx-large")
ax[1].legend(fontsize="xx-large")

plt.show()

calculate the The logistic regression on tenserflow model

In [ ]:
# print("hello")
import numpy as np
import pandas as pd
import  matplotlib.pyplot  as plt


In [ ]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32) # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32)  # 2-D Matrix
# print(X_train.reshape(-1,1))
# print(Y_train)

In [ ]:
pos = Y_train==1
# pos = Y_train==0

neg = Y_train==0
size,ax = plt.subplots(1,figsize=(8,5))
ax.scatter(X_train[pos],Y_train[pos],marker="x",c="r")
ax.scatter(X_train[neg],Y_train[neg],marker="o",c="b")


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import BinaryCrossentropy,MeanSquaredError

In [3]:
model = Sequential([tf.keras.layers.Dense(1,input_dim =1,activation="sigmoid",name="L1")])


In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [5]:
logistic_layer = model.get_layer("L1")
# logistic_layer
w,b = logistic_layer.get_weights()
print(w,b)


[[0.7941171]] [0.]


In [6]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
logistic_layer.set_weights([set_w,set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [9]:
def load_coffee_data():
    """ Creates a coffee roasting data set.
        roasting duration: 12-15 minutes is best
        temperature range: 175-260C is best
    """
    rng = np.random.default_rng(2)
    X = rng.random(400).reshape(-1,2)
    X[:,1] = X[:,1] * 4 + 11.5          # 12-15 min is best
    X[:,0] = X[:,0] * (285-150) + 150  # 350-500 F (175-260 C) is best
    Y = np.zeros(len(X))
    
    i=0
    for t,d in X:
        y = -3/(260-175)*t + 21
        if (t > 175 and t < 260 and d > 12 and d < 15 and d<=y ):
            Y[i] = 1
        else:
            Y[i] = 0
        i += 1

    return (X,Y.reshape(-1,1))
X,Y = load_coffee_data()

In [10]:
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X)
Xn  = norm_l(X)
print(np.max(Xn[:,0]))

1.6597537


In [11]:
print(len(Xn))

200


In [12]:
Xt = np.tile(Xn,(1000,1))
print(len(Xt[0]))

2


In [13]:
# Xt = np.tile(Xn,(1000))
# len(Xt[0])
Yt = np.tile(Y,(1000,1))

In [15]:
tf.random.set_seed(1234)
model = Sequential([Input(shape=(2,)),
Dense(3,activation='sigmoid',name = 'layer1'),
Dense(1,activation='sigmoid',name = 'layer2'),
])

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [17]:
L1_num_params = 2 * 3 + 3   # W1 parameters  + b1 parameters
L2_num_params = 3 * 1 + 1   # W2 parameters  + b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  9 , L2 params =  4


In [18]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[ 1.0374069   0.2875024   0.6054542 ]
 [ 0.55408895 -0.10266924  0.42084217]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-1.0191844]
 [ 0.9591683]
 [-0.7720111]] 
b2(1,): [0.]


In [31]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    Xt,Yt,
    epochs = 10,            
)

Epoch 1/10
6250/6250 [==============================] - 8s 1ms/step - loss: 7.2074e-06
Epoch 2/10
6250/6250 [==============================] - 7s 1ms/step - loss: 1.2591e-05
Epoch 3/10
6250/6250 [==============================] - 7s 1ms/step - loss: 4.9712e-06
Epoch 4/10
6250/6250 [==============================] - 7s 1ms/step - loss: 4.2249e-05
Epoch 5/10
6250/6250 [==============================] - 8s 1ms/step - loss: 1.3707e-05
Epoch 6/10
6250/6250 [==============================] - 7s 1ms/step - loss: 4.2881e-06
Epoch 7/10
6250/6250 [==============================] - 7s 1ms/step - loss: 1.1415e-05
Epoch 8/10
6250/6250 [==============================] - 7s 1ms/step - loss: 9.9794e-05
Epoch 9/10
6250/6250 [==============================] - 7s 1ms/step - loss: 5.7140e-06
Epoch 10/10
6250/6250 [==============================] - 7s 1ms/step - loss: 3.3368e-05


In [30]:
W1_1,b1_1 = model.get_layer("layer1").get_weights()
print(W1)
W2_1,b2_1 = model.get_layer("layer2").get_weights()
print(W2)

[[-0.33198068 21.3858     18.910374  ]
 [-9.442187    0.40114433 15.809253  ]]
[[-122.886215]
 [  99.00937 ]
 [-111.35261 ]]


In [33]:
W1_10,b1_10 = model.get_layer("layer1").get_weights()
print(W1)
W2_10,b2_10 = model.get_layer("layer2").get_weights()
print(W2)

[[-0.45160276 22.305038   19.359228  ]
 [-9.43275     0.40254402 16.107515  ]]
[[-128.45157 ]
 [ 103.274734]
 [-117.79746 ]]


In [34]:
X_test = np.array([
    [200,13.9],  # postive example
    [200,17]])   # negative example
X_testn = norm_l(X_test)
predictions = model.predict(X_testn)
print("predictions = \n", predictions)

1/1 [==============================] - 0s 71ms/step
predictions = 
 [[9.9999911e-01]
 [7.8198274e-17]]


In [35]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [0.]]
